version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - redis

  frontend:
    build: .
    ports:
      - "5174:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  redis-data: 